services:
  - type: web
    name: selenium-automation-dashboard
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
