# Base Application Configuration
url=https://www.saucedemo.com
browser=chrome
headless=false

# Timeouts in Seconds
implicit.wait=10
explicit.wait=30
page.load.timeout=60

# Reporting and Screenshots
report.path=reports/ExtentReport.html
screenshot.path=reports/screenshots/
override.reports=true

# Logging Configuration
log.level=INFO
